_site/config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  post 'user_sessions/new'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  get 'user_sessions/create'

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_reset, only: [:new, :create, :edit, :update]

  resources :contacts
  root 'contacts#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Address Book</title>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<div class="nav-bar clear">
		<div class="nav-links">
			<h1>Address Book</h1>
			<ul>
				<% if logged_in? %>
					<li>
						<span class="nav-mobile"><%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_contact_path, class: "nav-left" %>
						</span>
						<span class="nav-wide"><%= link_to "New Contact", new_contact_path, class: "nav-left" %>
						</span>
					</li>
					<li>
						<span class="nav-mobile"><%= link_to '<i class="fa fa-sign-out"></i>'.html_safe, logout_path, method: :delete, class: "nav-right" %>
						</span>
						<span class="nav-wide"><%= link_to "Sign Out", logout_path, method: :delete, class: "nav-right" %>
						</span>
					</li>
					<li>
						<span class="nav-mobile"><%= link_to '<i class="fa fa-cog"></i>'.html_safe, edit_user_path(current_user), class: "nav-left-top" %>
						</span>
						<span class="nav-wide"><%= link_to "Profile", edit_user_path(current_user), class: "profile" %>
						</span>
					</li>
				<% else %>					
					<li>
						<span class="nav-mobile"><%= link_to '<i class="fa fa-chevron-up"></i>'.html_safe, new_user_path, class: "nav-right" %>
						</span>
						<span class="nav-wide"><%= link_to "Register", new_user_path, class: "nav-right" %>
						</span>
					</li>
				<% end %>
			</ul>	
		</div>
	</div>
	<div class="body-wrapper">
		<%= render partial: "layouts/flash" %>

		<%= yield %>
	</div>

</body>
</html>