_site/config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  post 'user_sessions/new'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  get 'user_sessions/create'

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_reset, only: [:new, :create, :edit, :update]

  resources :contacts
  root 'contacts#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

_site/app/models/contact.rb
class Contact < ActiveRecord::Base

	belongs_to :user

	validates :first_name, presence: true
	validates :last_name, presence: true,
											  length: { minimum: 2 }
	validates :street, presence: true,
										 length: { minimum: 4 }
	validates :city, presence: true,
									 length: { minimum: 2 }
	validates :state, presence: true,
									  length: { minimum: 2 }
	validates :zip_code, presence: true,
											 length: { is: 5 },
											 format: {
											 	with: /[0-9]/
											 }

end

_site/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_user
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.all
    @ordered_contacts = current_user.contacts.sort_by { |c| [c.last_name.downcase, c.first_name.downcase] }
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = current_user.contacts.find(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = current_user.contacts.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :street, :city, :state, :zip_code, :phone_number, :contact_email)
    end
end

_site/app/helpers/contacts_helper.rb
module ContactsHelper
end

_site/app/views/contacts/edit.html.erb
<h1>Edit contact</h1>

<%= render 'form' %>

<%= link_to 'Back', @contact, class: "back" %>
<%= link_to 'Home', contacts_path, class: "back" %>

_site/app/views/contacts/index.html.erb
<h2 class="contacts-heading">Contacts</h2>

<div class="contacts-header">
  <ul>
  <% ('A'..'Z').each do |letter| %>
    <li>
    <a href="#<%= letter %>"><%= letter %></a>
    </li>
  <% end %>
  </ul>
</div>  
  
<div class="contacts-wrapper">
  <% ('A'..'Z').each do |letter| %> 
      
    <div id='<%= letter %>' class="letter-header">
      <%= letter %>
    </div>

    <% @ordered_contacts.each do |contact| %>
      <% if contact.last_name.downcase.first == letter.downcase %>
  	
  		        
        <div class="contact">      
  	      <%= link_to contact do %>
  	        <%= contact.first_name %> <%=contact.last_name %>        
  	      <% end %>
       </div>
      <% end %>
    <% end %>   
  <% end %>
</div>

<br>

_site/app/views/contacts/new.html.erb
<h2>New contact</h2>

<%= render 'form' %>

<%= link_to 'Back', contacts_path, class: "back" %>

_site/app/views/contacts/show.html.erb
	<div class="contact-show">
		<h1>
			<%= @contact.first_name %> <%= @contact.last_name %>
		</h1>

		<ul>
		  <li><%= @contact.street %></li>
		  <li><%= @contact.city %>, <%= @contact.state %> <%= @contact.zip_code %></li>
		  <li><%= @contact.phone_number %></li>
		  <li class="email-link"><%= mail_to @contact.contact_email %></li>
		</ul>
	</div>
	<br />

<footer>
	<span class="nav-mobile contact-footer-icon">
		<%= link_to '<i class="fa fa-home"></i>'.html_safe, contacts_path %>
	</span>
	<span class="nav-wide">
		<%= link_to 'Home', contacts_path, class: "back" %>
	</span>

	<span class="nav-mobile contact-footer-icon">
		<%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_contact_path(@contact) %>
	</span>
	<span class="nav-wide">
		<%= link_to 'Edit', edit_contact_path(@contact), class: "back" %>
	</span>

	<span class="nav-mobile contact-delete-icon">
		<%= link_to '<i class="fa fa-ban"></i>'.html_safe, @contact, method: :delete, data: { confirm: "Are you sure you want to delete this contact?" } %>
	</span>
	<span class="nav-wide">
		<%= link_to "Delete", @contact, class: "back warning", method: :delete, data: { confirm: "Are you sure you want to delete this contact?" } %>
	</span>	
</footer>